### ISSUE TITLE
Migrate JupyterHub deployment from Helm 2 to Helm 3

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/bridge-data-platform#65]
Helm 2 will be officially deprecated soon so the deployment should probably be migrated to Helm 3.

Blog with instructions on achieving this with the helm 2to3 plugin here: https://helm.sh/blog/migrate-from-helm-v2-to-helm-v3/

@annahadji I don't know how stuck into kubernetes/helm you got on this project. I can either do this, or we could co-work it if you like? I'm going to try on [Hub23](https://github.com/alan-turing-institute/hub23-deploy) first.

**Comment by annahadji** [comment]
Hi @sgibson91, I re-deployed the platform with Helm 3 when I was enabling the [HTTPS](https://github.com/alan-turing-institute/bridge-data-platform/issues/7#issuecomment-694225010) and refactoring a couple of things, so I think we can close this issue? I'll add some clearer documentation about the version of Helm.
The jupyterhub is down currently because the Azure account was disabled at the beginning of October (we need to apply for new credits).

**Comment by sgibson91** [comment]
Fab! In which case, I know who to ask if I have any trouble 😉
